### ISSUE TITLE
Question re:stream initiation

### ISSUE THREAD

**Issue by princemaple** [feross/simple-peer#161] opened 2017-04-01 07:19 UTC
Hi @feross ,

Thanks a lot for the great library.

Is it true that you can only get the stream from your peer if the initiator shares a stream?
That is, if the initiator was not setup with a stream, even if the peer (NOT the initiator) shared a stream, the initiator wouldn't get it.

Thanks,
Po

**Comment by RationalCoding** [comment] 2017-04-01 21:21
@princemaple No, you can attach any combination of media streams.

There's a bug in Chrome that causes the stream event to not fire if the initiator doesn't share a stream. Set the offer/answer constraints as a workaround.

Closing as duplicate of #95.

**Closed by RationalCoding** 2017-04-01 21:21 UTC

**Comment by princemaple** [comment] 2017-04-01 21:59
Thank you!

**Comment by princemaple** [comment] 2017-04-01 22:00
BTW I got that behavior in Firefox as well. Not sure if it's the same bug.

**Comment by RationalCoding** [comment] 2017-04-01 22:04
@princemaple I haven't experienced it on Firefox, but it might be the same thing if setting the constraints fixes it.

I have a project with one-way media streams from the non-initiator and so far no problems on any browser, so everything should be OK.

**Comment by princemaple** [comment] 2017-04-01 23:44
Yeah the workaround fixes it on Firefox too, so probably the same problem.
