### ISSUE TITLE
iPhone to iPhone not working

### ISSUE THREAD

**Issue by dnish** [feross/simple-peer#317] opened 2018-05-31 11:38 UTC
Hey guys,
I'm having an issue when I try to connect 2 iPhones via video chat. The connection doesn't get established. We've also tried to change the initiators, but the problem is still there. STUN and TURN server are set. This is what I get when I log the signaling events:

<img width="1279" alt="bildschirmfoto 2018-05-31 um 13 35 14" src="https://user-images.githubusercontent.com/7636313/40780128-a821e52a-64d7-11e8-9386-81601b6ba3b3.png">

Any idea why I don't get any candidates? Both iPhones are on the latest iOS. My colleague is from the same city - the only difference is that he uses another internet provider.

**Comment by nazar-pc** [comment] 2018-05-31 11:44
Can you provide SDP as actual string instead of screenshot? Are you using latest version of `simple-peer`?

**Comment by dnish** [comment] 2018-05-31 11:58
Hey @nazar-pc,
thank you for the answer. This is the actual log as string:

```
"v=0
o=- 7810647351382468552 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video data
a=msid-semantic: WMS 83d05f7d-6a1d-497a-944a-748363388a1c
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:CB50
a=ice-pwd:kNLNIWaAmabgOOvDuHAxBwQ7
a=ice-options:trickle
a=fingerprint:sha-256 6C:CF:A0:26:A3:FB:E1:3C:71:82:5E:0C:F3:0E:33:56:30:5A:9C:B9:48:EB:C4:98:09:D4:B0:C8:8D:D2:36:9A
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2884124594 cname:jRvODwrA7dUcbBwb
a=ssrc:2884124594 msid:83d05f7d-6a1d-497a-944a-748363388a1c fa5e5828-2fe4-4088-a68c-7b6b384cb90b
a=ssrc:2884124594 mslabel:83d05f7d-6a1d-497a-944a-748363388a1c
a=ssrc:2884124594 label:fa5e5828-2fe4-4088-a68c-7b6b384cb90b
m=video 9 UDP/TLS/RTP/SAVPF 96 98 99 97 100
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:CB50
a=ice-pwd:kNLNIWaAmabgOOvDuHAxBwQ7
a=ice-options:trickle
a=fingerprint:sha-256 6C:CF:A0:26:A3:FB:E1:3C:71:82:5E:0C:F3:0E:33:56:30:5A:9C:B9:48:EB:C4:98:09:D4:B0:C8:8D:D2:36:9A
a=setup:active
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 red/90000
a=rtpmap:98 ulpfec/90000
a=rtpmap:99 H264/90000
a=rtcp-fb:99 ccm fir
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 transport-cc
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=ssrc-group:FID 3981868784 2780000186
a=ssrc:3981868784 cname:jRvODwrA7dUcbBwb
a=ssrc:3981868784 msid:83d05f7d-6a1d-497a-944a-748363388a1c 47179403-4310-4763-8724-4f4e4d8bba9e
a=ssrc:3981868784 mslabel:83d05f7d-6a1d-497a-944a-748363388a1c
a=ssrc:3981868784 label:47179403-4310-4763-8724-4f4e4d8bba9e
a=ssrc:2780000186 cname:jRvODwrA7dUcbBwb
a=ssrc:2780000186 msid:83d05f7d-6a1d-497a-944a-748363388a1c 47179403-4310-4763-8724-4f4e4d8bba9e
a=ssrc:2780000186 mslabel:83d05f7d-6a1d-497a-944a-748363388a1c
a=ssrc:2780000186 label:47179403-4310-4763-8724-4f4e4d8bba9e
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:CB50
a=ice-pwd:kNLNIWaAmabgOOvDuHAxBwQ7
a=ice-options:trickle
a=fingerprint:sha-256 6C:CF:A0:26:A3:FB:E1:3C:71:82:5E:0C:F3:0E:33:56:30:5A:9C:B9:48:EB:C4:98:09:D4:B0:C8:8D:D2:36:9A
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
" = $1
```

**Comment by nazar-pc** [comment] 2018-05-31 12:11
You may be on restricted network, try testing your TURN server here: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
It should give the same results as simple-peer, but in more convenient UI.

**Comment by dnish** [comment] 2018-05-31 12:29
Hey,
this is what we get on our device:

<img width="719" alt="bildschirmfoto 2018-05-31 um 14 28 02" src="https://user-images.githubusercontent.com/7636313/40782215-e64a9160-64de-11e8-96cc-80a445baadd8.png">

And this are the logs that we get on the other device:

![da4744b1-94ce-463c-b6a5-8984ba75ed3c](https://user-images.githubusercontent.com/7636313/40782246-faa1f4d2-64de-11e8-9475-7112a7e90980.jpeg)

**Comment by nazar-pc** [comment] 2018-05-31 12:33
Then connections should theoretically work.

Are you aware that there might be multiple `signal` events (unless you specify `tricke: false` that will make connection establishment slower) and are you forwarding all of them to the other side of conversation?

**Comment by dnish** [comment] 2018-05-31 12:37
Hey,
yeah, we forward all of them to the other user. On my side, 60% of the connections to other users are working, but there are still 40% with the same issue (no candidates). If I use the network of my colleague, I'm not able to connect to any other user (still using the same device). For testing I've also set the following config entry:

```
iceTransportPolicy: "relay", // Force TURN
```

**Comment by nazar-pc** [comment] 2018-05-31 12:50
You can try enabling debugging mode and see what happens under the hood. I don't have any Apple devices at all to reproduce this. Maybe @RationalCoding have some ideas.

**Comment by dnish** [comment] 2018-05-31 12:53
Ah cool, how can I enable debug mode (didn't find any info in the docs)?

**Comment by nazar-pc** [comment] 2018-05-31 12:55
```javascript
localStorage.debug = 'simple-peer'
```

**Comment by dnish** [comment] 2018-05-31 15:50
Okay, after some debugging I've recognized that the peer object isn't available on the first message. I'm just wondering how I have to deal with it? In our application, a user creates a call and sends a REDIS message to another user. If the user accepts it, we do the following:

```
   async acceptCall(foreignUserId) {
        await this.createPeer(false,foreignUserId);
        Meteor.call("rtcMessages.send", foreignUserId, {type: 'call.accepted', data: null});

    }
```
false means that the user isn't the initiator. On the initiator side, we run the <code>call.accepted</code> function, which only includes:

```
   this.createPeer(true,message.fromUserId);
```

The problem is that the receiver immediately starts sending signaling messages, but the Peer oject wasn't created yet. 

```
 case 'call.signaling':
                    if(this.peer) this.peer.signal(message.data); // Having issue that regonitate message is firing before creating the peer
                    break;
``` 

Any idea how I could prevent this? Is it possible to delay the first signaling message?

**Comment by nazar-pc** [comment] 2018-05-31 15:59
Create `Promise` or some kind of callback and only call `this.peer.signal()` when `this.signal()` exists. This depends heavily on the architecture of the application. You can also store signals on initiator's side and only send then when/if receiver accepts incoming call, at which point `this.peer` will be ready on receiver's side.

**Comment by dnish** [comment] 2018-06-01 10:49
Ah okay, yeah, just fixed it but that didn't solve the problem. Is it possible that DS-Lite causes this problem? The ISP of my friend uses this mechanism to use one IPv4 address for multiple users. I'm just wondering if this mechanism could cause problems with TURN?

**Comment by nazar-pc** [comment] 2018-06-01 10:55
I have no idea what is that, but generally if you use TURN over port that is not blocked by ISP/firewall, it should work. If it happens on ISP level, you'll be able to debug it on desktop via browser's WebRTC debugging features, they are present in Firefox, Chromium and probably Safari too.
Closing issue now, since it doesn't seem to be simple-peer's bug.

**Comment by dnish** [comment] 2018-06-01 10:58
@nazar-pc It means that the client is not able to open any ports on his public IPv4 address because it is used by multiple clients. This feature is used by multiple ISPs here in Germany (f.e. NetCologne or Unitymedia/UPC) because they don't have enough IPv4 addresses.

**Closed** 2018-06-01 10:59 UTC
Labels: question

**Comment by nazar-pc** [comment] 2018-06-01 11:01
It shouldn't be a problem with TURN, since instead of opening public port, you connect to TURN server and use it as relay. In any case, if https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ shows that relay is working, you can dig into debugging tools of your browser and see live what it does and where exactly it fails.

**Comment by dnish** [comment] 2018-06-01 11:28
For anyone who has similar issues: We needed to add the IPv6 addresses seperately to our config. Before we only used turn.ourapp.com which has AA and AAAA DNS entries. This config solved the issue:


        iceServers: [
                        {   urls: 'stun:stun.l.google.com:19302'},
                        {   urls: 'stun:global.stun.twilio.com:3478?transport=udp'},
                        {   urls: 'stun:66.102.1.127:19302'},
                        {   urls: 'stun:[2A00:1450:400C:C06::7F]:19302'},
                        {
                            urls: 'turn:1.2.3.4:80?transport=udp',
                            credential: 'a',
                            username: 'a'
                        },
                        {
                            urls: 'turn:[IP]:80?transport=udp',
                            credential: 'a',
                            username: 'a'
                        },

                        {
                            urls: 'turn:1.2.3.4:80?transport=tcp',
                            credential: 'a',
                            username: 'a'
                        },

                        {
                            urls: 'turn:[IP]:80?transport=tcp',
                            credential: 'a',
                            username: 'a'
                        },


                    ]

**Comment by nazar-pc** [comment] 2018-06-01 11:32
Looks like implementation bug. Did it happen in all browsers or just some?

**Comment by dnish** [comment] 2018-06-01 11:35
Yeah, in all. I've also tried to connect from an iPhone (my) to Chrome Windows (friend) - but that didn't work either. It must be a special network issue, I guess it's a problem with IPv6. He was not able to connect to ANY other user. I've copied the config style from www.appr.tc - and now it is working without any problems :-).

**Comment by dnish** [comment] 2018-06-01 16:44
@nazar-pc We just noticed another problem that occurs with some users of our chat application. This is what I get when I'm the initiator and the other user accepts the call: 

<img width="1064" alt="bildschirmfoto 2018-06-01 um 18 39 46" src="https://user-images.githubusercontent.com/7636313/40852601-3794b2f2-65cb-11e8-9069-80d6385c2649.png">

In this case, the video chats ends instantly. Now, If we change the roles (he is the initator) I get the following on my side:

<img width="1917" alt="bildschirmfoto 2018-06-01 um 18 41 32" src="https://user-images.githubusercontent.com/7636313/40852655-6db0cbe6-65cb-11e8-9c2c-66de59d7a85a.png">


The video chat ends on his side, on my side it stays opened but I can't see any stream (close event not firing). I'm on latest iOS (iPhone) he has the following user agent: <code>Android 7.0; SAMSUNG SM-T580 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87</code>

Do you recognize anything unusual within the logs?

**Comment by nazar-pc** [comment] 2018-06-01 16:57
I'd place breakpoint in `destroy` function and check where it comes from and why, nothing suspicious from the logs above.
