### ISSUE TITLE
Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS

### ISSUE THREAD

**Issue by adammw** [feross/simple-peer#30] opened 2015-07-06 11:57 UTC
When Trickle ICE is enabled, I get the following error when trying to establish a peer connection between two Chrome browsers on the same machine:

    Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS

Disabling Trickle ICE, everything works smoothly.

The code I'm testing with is in a gist: https://gist.github.com/adammw/d9bf021c395835427aa0

**Comment by feross** [comment] 2015-07-06 23:19
What version of node, simple-peer, and which browser are you using? Your example works fine for me.

**Comment by feross** [comment] 2015-07-06 23:21
Btw, you shouldn't add a new set of event listeners in `socket.on('receivePeerSignal', function(data) {` because that will get called multiple times with each bit of signaling data and you'll end up handling the 'connec't and 'data' events multiple times.

**Comment by feross** [comment] 2015-07-08 17:16
I'm closing this, as I can't reproduce it. It works for me. If you have new information you can provide to help narrow this down, please comment or open a new issue. Thanks!

**Closed by feross** 2015-07-08 17:16 UTC
Labels: need more info

**Comment by adammw** [comment] 2015-07-10 14:09
@feross yep, I believe my mis-signalling was to blame here. thanks!
For reference I've updated my gist and and confirm it works correctly.

**Comment by mayeaux** [comment] 2017-12-26 04:22
Thanks that actually helped save me on another project I was working on :)
