### ISSUE TITLE
Should not call this.destroy when catch error on already closed datachannels

### ISSUE THREAD

**Issue by mssparker** [feross/simple-peer#627] opened 2020-04-20 12:56 UTC
Hi, per https://bugs.chromium.org/p/chromium/issues/detail?id=1069811 it seems that errors fires on already closed datachannels, simple-peer catch error in this._channel.onerror and call this.destroy.

Can you please add a condition with check this._channel.readyState !== 'closed' in this._channel.onerror or _destroy

**Comment by t-mullen** [comment] 2020-05-03 16:02
An actual error could be thrown when `this._channel.readyState === 'closed'` that would warrant calling destroy.

Do we have any method of determining if the error is "real" or not? Is `error.message` something unique? I'm not able to reproduce this.

**Comment by mssparker** [comment] 2020-05-04 13:26
yes, error is unique, in my case it 'Transport channel closed'.
same case like here https://bugs.chromium.org/p/chromium/issues/detail?id=1069811

**Comment by feross** [comment] 2020-06-02 02:47
I've run into this too. It looks like Chrome fixed the issue. Can this issue be closed?

**Comment by t-mullen** [comment] 2020-08-09 20:21
This is fixed in Chrome 84.0.4147.105 and Chromium: 83.0.4103.116.

**Closed by t-mullen** 2020-08-09 20:21 UTC
Labels: bug, dependency/browser
