### ISSUE TITLE
Facing issue while sharing screen after few times

### ISSUE THREAD

**Issue by amitmeghare** [feross/simple-peer#625] opened 2020-04-20 08:02 UTC
Hi,

Facing issue while sharing a screen. It starts screen sharing & opens the camera properly after stop sharing on the first & second time, but when I trigger stop screen sharing event on the second time, it stops the signal/streaming on the other user's screen. Following are my two functions code startScreenShare & stopScreenShare in which I am removing and adding stream, and attached is the console screenshot, in which events log are shown. I am using Vuejs, Pusher, Simple-Peer with Laravel Framework.

startScreenShare: function() {

          console.log('Start Screen Share');
          try {
            this.$refs.myVideo.srcObject.getTracks().forEach(t => t.stop());
          } catch(e) {
            this.$refs.myVideo.src.getTracks().forEach(t => t.stop());
          }

          this.getScreenMediaPermissions()
              .then((stream) => {
                try {
                  this.$refs.myVideo.srcObject = stream;
                } catch(e) {
                  this.$refs.myVideo.src = window.URL.createObjectURL(stream);
                }

                this.$refs.myVideo.play();

                this.peer.removeStream(this.stream);
                this.peer.addStream(stream);
                this.stream = stream;
              })
              .catch((err) => {
                this.state.hasMedia = false;
              });
          this.isScreenShare = true;
        },

        stopScreenShare: function() {
          console.log('Stop Screen Share');
          try {
            this.$refs.myVideo.srcObject.getTracks().forEach(t => t.stop());
          } catch(e) {
            this.$refs.myVideo.src.getTracks().forEach(t => t.stop());
          }

          this.getMediaPermissions()
              .then((stream) => {
                try {
                  this.$refs.myVideo.srcObject = stream;
                } catch(e) {
                  this.$refs.myVideo.src = window.URL.createObjectURL(stream);
                }

                this.$refs.myVideo.play();

                this.peer.removeStream(this.stream);
                this.peer.addStream(stream);
                this.stream = stream;
              })
              .catch((err) => {
                this.state.hasMedia = false;
              });

          this.isScreenShare = false;
        }

![screenshot--2020 04 20-12_56_48](https://user-images.githubusercontent.com/25700375/79726137-f3695e00-8307-11ea-956c-48b71d8d4dc5.png)

_Originally posted by @amitmeghare in https://github.com/feross/simple-peer/issues/613#issuecomment-616377803_

**Comment by nazar-pc** [comment] 2020-04-20 08:53
Why do you think it is an issue with simple-peer?

**Comment by amitmeghare** [comment] 2020-04-20 13:46
I think this (attached file) is the actual issue. But how it is increasing size. I am removing the old stream and then adding a new stream to the peer, and this data is generated by the peer. In the pusher document, it says "The data content (POST body) of events must be smaller than 10kB."

Mentioned pusher error link: https://pusher.com/docs/channels/server_api/http-api#publishing-events

Is anybody knows about this, please let me know. 

![screenshot-127 0 0 1_8000-2020 04 20-19_05_55](https://user-images.githubusercontent.com/25700375/79758163-a9e63680-833a-11ea-946e-bccbfac492c6.png)

**Comment by nazar-pc** [comment] 2020-04-20 13:49
Didn't have a chance to work with pusher before, so can't really help. I would suggest you to give `replaceTrack` a try, it should do what you need in this instance and as a bonus will avoid renegotiation with ever growing SDP altogether.

I'm closing the issue since it doesn't seem to be caused by simple-peer, but feel free to continue conversation.

**Closed by nazar-pc** 2020-04-20 13:49 UTC
Labels: question

**Comment by amitmeghare** [comment] 2020-04-21 05:03
> Didn't have a chance to work with pusher before, so can't really help. I would suggest you to give `replaceTrack` a try, it should do what you need in this instance and as a bonus will avoid renegotiation with ever growing SDP altogether.
> 
> I'm closing the issue since it doesn't seem to be caused by simple-peer, but feel free to continue conversation.

Hey,

Its perfectly work for me. Thank you so much :) you are awesome.
