### ISSUE TITLE
addStream closes the peer connection

### ISSUE THREAD

**Issue by jiangts** [feross/simple-peer#528] opened 2019-08-06 09:03 UTC
After establishing a peer connection, addStream calls the `peer.on('close'...)` event. Using data channels works perfectly fine.

Then, I get `Uncaught Error: cannot signal after peer is destroyed`

My guess is it has to do with the `_stream_readable` programmatically calling destroy...

**Comment by jiangts** [comment] 2019-08-06 17:38
ok, I found that my issue was I was adding too many `peer.on` listeners, which seems unrelated but by changing it to `peer.once` the peer stopped closing on me

**Comment by t-mullen** [comment] 2019-08-11 16:03
Closing since it seems like this issue was resolved. Feel free to reopen with reproduction steps if that's not the case.

**Closed by t-mullen** 2019-08-11 16:03 UTC

**Comment by jiangts** [comment] 2019-08-12 05:34
hmm, I think it's worth investigating if adding too many `peer.on` listeners causes the peer connection to close.  If it's desired behavior, I think it should be mentioned on the README.
