### ISSUE TITLE
XAMPP

### ISSUE THREAD

**Issue by cannothing** [feross/simple-peer#608] opened 2020-04-05 07:56 UTC
I am just testingthe examples on my local server(Xampp). Is it possible to use xampp?

**Comment by nazar-pc** [comment] 2020-04-05 08:22
XAMPP has nothing to do with simple-peer, can you clarify the question?

**Comment by cannothing** [comment] 2020-04-05 10:18
I putted the files in a subfolder of the htdocs-folder of xampp and used two browsers to test the first example of https://github.com/feross/simple-peer/blob/master/README.md with  Chrome and FF.

 

No reaction. Doing the same uploding the files to my external webspace, everything worked fine.

 

 

 

Von: Nazar Mokrynskyi <notifications@github.com> 
Gesendet: Sonntag, 5. April 2020 10:22
An: feross/simple-peer <simple-peer@noreply.github.com>
Cc: cannothing <ich@stephan-zitzmann.de>; Author <author@noreply.github.com>
Betreff: Re: [feross/simple-peer] XAMPP (#608)

 

XAMPP has nothing to do with simple-peer, can you clarify the question?

**Comment by nazar-pc** [comment] 2020-04-05 12:07
readme.md і а document you should read and understand. Also those example are designed to either run on the same page or for you to open console and manually send signaling data between browsers. In production that would be done by signaling server.
It not something you can blindly copy to the web-server root directory as is and expect for something to just happen on its own.
So this is fully expected behavior.

I can suggest you to read about what WebRTC is and how to set it up. simple-peer just makes working with it easier. There have been many questions here about such topic already, you'll b able to find some good answers. It is really hard to explain basics to everyone every time :disappointed: 

Closing since there is nothing wrong with simple-peer here, but feel free to continue conversation.

**Closed by nazar-pc** 2020-04-05 12:07 UTC
Labels: question

**Comment by jarretttaylor** [comment] 2020-04-05 17:37
@cannothing I believe WebRTC requires HTTPS which is likely why it was not working locally for you under XAMPP.

**Comment by nazar-pc** [comment] 2020-04-05 17:40
`localhost` should be in exceptions and work too
