### ISSUE TITLE
Adding second stream to connection does not fire onstream event.

### ISSUE THREAD

**Issue by adik6555** [feross/simple-peer#762] opened 2020-11-10 15:24 UTC
Hey,
So I am trying to add a second stream to an existing simple peer connection, but I have no way of handling it on the other side.
My code looks as following:
```javascript
let localVideoInput = document.querySelector("#video-input");
localVideoInput.addEventListener("added-video", () => {
  localVideo = document.querySelector("#local-video");
  localVideo.addEventListener("loadedmetadata", async () => {
    stream = localVideo.captureStream();
    await myPeers.forEach((peer) => {
      peer["peer"].addStream(stream);
    });
    socket.emit("added-video", ROOM_ID);
  });
});

socket.on("added-video", () => {
  console.log("received added video event");
  myPeers.forEach((peer) => {
    console.log(peer["peer"].streams[0].getTracks());
    peer["peer"].on("stream", () => {
      console.log("received stream");
    });
    peer["peer"].on("track", () => {
      console.log("received track");
    });
  });
});
```
`myPeers` is an array containing all current users' peers.

The issue is, onstream or ontrack events never fire.

**Comment by feross** [comment] 2020-11-10 23:46
This is not a support forum. Please provide a minimal reproducible example that demonstrates your issue. 
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Closed by feross** 2020-11-10 23:46 UTC
