### ISSUE TITLE
sending signaling message even when initiator is set to false

### ISSUE THREAD

**Issue by Dealerpriest** [feross/simple-peer#372] opened 2018-10-18 11:54 UTC
I'm developing a ionic app for android.
I use the simple-peer library to create a webRTC connection between two phones.

```
    this.peer = new Peer({
      initiator: false,
      stream: this.localStream,
      config: {
        iceServers: [
          { urls: "stun:stun.l.google.com:19302" },
          {
            urls: "turn:1.1.1.1:3333",
            username: "blablabla",
            credential: "blablabla"
          }
        ]
      }
    });
    this.peer.on("signal", data => {
      console.log("Got signal data locally. Passing it on to signaling server");
      this.socket.emit("signal", data);
    });
    this.peer.on("stream", stream => {
      console.log("I am Robot and I am listener. Received stream from initiating peer");
      // got remote video stream, now let's show it in a video tag
      let video: HTMLVideoElement = document.querySelector("#remote-video");
      video.srcObject = stream;
      video.play();
    });
```
This will result in my signaling server (socket.io-server) receiving a signal message. The documentation states that if inititator is false, the signal event won't get triggered before an offer is received. That doesn't seem to be the case.

**Comment by t-mullen** [comment] 2018-10-18 12:07
Duplicate of #366

**Closed by t-mullen** 2018-10-18 12:07 UTC
