### ISSUE TITLE
Tests are stalling again

### ISSUE THREAD

**Issue by feross** [feross/simple-peer#348] opened 2018-07-27 07:25 UTC
It's unclear what's going on.

**Comment by RationalCoding** [comment] 2018-07-30 22:27
Do you have a link to the build that stalled? I can't seem to find it.

**Comment by t-mullen** [comment] 2018-10-14 21:35
Not sure if this is the same stall, but the latest build stalled on electron-webrtc - send data before "connect" event. The data is getting through, but peer2 is not ending or finishing.

The problem is Chromium datachannels getting stuck in the "closing" state (this bug is fixed in newer versions). I worked around this with a timeout in #334 that I'll port as a separate patch since multiplexing still doesn't work on electron-webrtc.

**Comment by t-mullen** [comment] 2018-11-06 09:19
I believe I've solved both of the problems stalling the tests. 👍

**Closed by t-mullen** 2018-11-06 09:19 UTC
