### ISSUE TITLE
Error when initiator is true

### ISSUE THREAD

**Issue by kumavis** [feross/simple-peer#56] opened 2015-12-27 06:22 UTC
```js
var peer = new Peer({ initiator: true })
```
produces error:
```
[57803:1226/220911:ERROR:webrtcsession.cc(1384)] ConnectDataChannel called when data_channel_ is NULL.
```
in electron via `electron-spawn`

setting initiator to `false` does not cause an error.

**Comment by feross** [comment] 2015-12-27 12:51
I'm not sure if this is a problem with `simple-peer`, `electron-spawn`, or `electron` itself.

We need to do a bit of digging. Please let me know if you have any more information about this.

**Comment by feross** [comment] 2015-12-27 17:30
I was able to reproduce this, but I have no idea what's causing it.

**Comment by kumavis** [comment] 2015-12-27 17:43
fwiw, this doesnt happen when I use `rtc-quickconnect` in electron

**Comment by feross** [comment] 2015-12-27 17:43
This actually doesn't seem to be causing any issues. Two peers can connect just fine, even though this gets printed.

**Comment by kumavis** [comment] 2015-12-27 17:44
oh interesting.. maybe i backed out too soon

**Comment by feross** [comment] 2015-12-27 17:57
Since this isn't causing any issues, I think I'll close this for now. If this starts to cause issues or you get more information, we can re-open :+1:

**Closed by feross** 2015-12-27 17:57 UTC
Labels: bug, need more info

**Comment by mmckegg** [comment] 2016-10-06 02:44
Under [ferment](https://github.com/mmckegg/ferment), this seems to come up continuously on my server (debian linux, headless with xfbv-run), but not when running locally on my mac.  

Really messing up my logs 😢 

Wonder what causes it?

**Comment by feross** [comment] 2016-10-06 04:27
@mmckegg It's a Chromium internal debug log that the team hasn't disabled yet. Here's an issue about it: https://bugs.chromium.org/p/chromium/issues/detail?id=579430

It's harmless, but annoying. Feel free to filter it out of stdout/stderr.

**Comment by feross** [comment] 2016-10-06 04:28
Related issue: https://github.com/feross/webtorrent-desktop/issues/85

**Comment by feross** [comment] 2016-10-06 06:05
And with one comment, they just fixed the bug: https://bugs.chromium.org/p/chromium/issues/detail?id=579430 Will take a while to make it through the Chromium release process, but yay!
