### ISSUE TITLE
'close' event not firing when iceConnectionState becomes 'disconnected'

### ISSUE THREAD

**Issue by aakilfernandes** [feross/simple-peer#553] opened 2019-09-25 19:08 UTC
In my code, I have a bunch of listeners

```
    this.simplePeer.on('iceStateChange', (iceConnectionState, iceGatheringState) => {
      console.log('ice', iceConnectionState, iceGatheringState)
    })

    this.simplePeer.on('connect', () => {
      console.log('connect')
    })

    this.simplePeer.once('error', () => {
      console.log('error')
    })
    this.simplePeer.once('close', () => {
      console.log('close')
    })
```

I start a two peers in seperate windows. They connect fine, then i close the second window. I'm expecting the peer to emit a `close` event, however none is fired.

Here's my console logs

```
index.js:23204 ice new gathering
index.js:23204 ice new complete
index.js:23204 ice new gathering
index.js:23204 ice new complete
index.js:23204 ice new gathering
index.js:23204 ice new complete
index.js:23204 ice new gathering
index.js:23204 ice checking gathering
index.js:23204 ice connected gathering
index.js:23204 ice connected complete
index.js:23207 connect
index.js:23204 ice disconnected complete
```

**Comment by lagmoellertim** [comment] 2019-09-25 21:13
Same for me, though `peer.destroy()` seems to work ok.
I also need the `close` event to work in order to do some peer cleanup

**Comment by t-mullen** [comment] 2019-09-25 22:02
Can you try the fix here? https://github.com/feross/simple-peer/pull/541

**Comment by lagmoellertim** [comment] 2019-09-26 00:00
Yes, #541 worked.
After closing one connection by closing the browser, it took ~15 secs and then the `close` event and the `error` event were called.

This is my `console.log` debug output:
```
**error** Error: Connection failed.
    at makeError (index.js:18)
    at Peer._onConnectionStateChange (index.js:707)
    at RTCPeerConnection.Peer._pc.onconnectionstatechange (index.js:119)

**close** <ConnectionID>
```

**Comment by t-mullen** [comment] 2019-09-26 00:02
Seems right. It takes about that long for the connection to timeout.

**Comment by t-mullen** [comment] 2019-09-26 00:02
Closing as duplicate of #532

**Closed by t-mullen** 2019-09-26 00:02 UTC
