### ISSUE TITLE
DataChannel never opening on initiator (react-native iOS)

### ISSUE THREAD

**Issue by poltak** [feross/simple-peer#571] opened 2019-12-10 08:17 UTC
Hi there.

I've been dealing with a WebRTC issue on a connection between an iOS device (the initiator) and desktop browser. The connection seems to hang, never establishing the connection or encountering any errors. The same code connecting an Android device (it's written in React Native) with a desktop browser works fine. 

After looking further into what's happening, I've seen that the created data channel \[0\] never receives the `open` event, thus never running the `onopen` listener \[1\]. This results in the channel's ready state not being set, causing `_maybeReady` calls to always return early.

Underneath we're using the [`react-native-webrtc`](https://github.com/react-native-webrtc/react-native-webrtc) WebRTC implementation.

My question is if anyone has encountered anything similar, or if anyone knows what would perhaps cause the data channel to never open?
Is there any more info I could provide to assist with working out what's happening?
The fact that the same code is running fine on Android is still a puzzle

\[0\]: https://github.com/feross/simple-peer/blob/18ea34e954d7029944f608bcc3f206bf4f39d6de/index.js#L135-L137
\[1\]: https://github.com/feross/simple-peer/blob/18ea34e954d7029944f608bcc3f206bf4f39d6de/index.js#L939-L944

**Comment by t-mullen** [comment] 2019-12-13 02:39
We don't do anything fancy with setting up the datachannel. I would try to reproduce without simple-peer. If it still occurs, open this issue in the `react-native-webrtc` repo.

I'd love to support react-native properly - getting the `simple-peer` test suite running in react-native would be a big step towards stability of both projects.

**Comment by buu700** [comment] 2020-01-19 04:52
I don't know whether it's an issue with simple-peer, iOS/Safari, webrtc-adapter, or something else, but I seem to be running into this issue as well in iOS Safari (not React Native).

**Comment by nazar-pc** [comment] 2020-01-19 11:24
Then your issue is different @butmitchtho. Create a separate issue if you have difficulties. Also try without adapter, it is not needed for simple-peer.

**Comment by buu700** [comment] 2020-01-19 17:42
Awesome, thanks @nazar-pc! I didn't realize that simple-peer handled

**Comment by buu700** [comment] 2020-01-19 17:49
Awesome, thanks @nazar-pc! I didn't realize that simple-peer handled cross-browser issues as well, but removing `webrtc-adapter` resolved my issue. I'm guessing it may be the case that it and `react-native-webrtc` both depend on a JS library that contains the root cause of this bug.

Is there any documentation on what simple-peer does cross-browser-wise (relying on prefixed versions of APIs when needed, importing certain polyfills, etc.) or what browsers it will support? I'm fine dropping support for ancient versions of evergreen browsers and/or pre-Chromium Edge if it means we can finally support iOS, but would be good to know exactly what tradeoff we're making (if any) for future reference. Not a big deal if that information isn't readily available though.

**Comment by nazar-pc** [comment] 2020-01-19 17:54
Simple-peer should work in any evergreen browser, including iOS I believe, except for the features browser physically doesn't support yet (those checks can be found in `test` directory).

**Comment by feross** [comment] 2020-11-02 22:55
Closing as there's no issue in `simple-peer` here!

**Closed by feross** 2020-11-02 22:55 UTC
Labels: bug, dependency/browser
