### ISSUE TITLE
Sending ArrayBuffer on Chrome v84 breaks data channel

### ISSUE THREAD

**Issue by KartoffelMann** [feross/simple-peer#712] opened 2020-07-23 06:17 UTC
I'm attempting to send an audio file from one peer to another in Chrome. I'm aware that there's no blob support in Chrome and I should use an ArrayBuffer in the peer.send(buffer) call. This code currently works in Firefox without fail or breaking the data channel.

`function sendBlob(blob, peer) {
        blob.arrayBuffer().then(
            buffer => {
                peer.send(buffer);
            }
        )
    }`

In this case I'm getting met with Uncaught RTCError: Failure to send data and 
![image](https://user-images.githubusercontent.com/26171342/88256664-df782400-cc89-11ea-826b-0d2e426893a6.png)

Is there anything I'm doing wrong that would cause Chrome to break in this case?

**Comment by nazar-pc** [comment] 2020-07-23 21:35
How big is your data? Did you chunk it to make sure it is under 16 kiB per message and made sure to check buffer threshold?

**Comment by KartoffelMann** [comment] 2020-07-23 21:37
I'm using ogg format and my files are under .5MB. Perhaps I need to chunk them, just seems odd that Chrome breaks in this case but Firefox isn't giving me any problems.

**Comment by nazar-pc** [comment] 2020-07-23 21:40
Yes, you definitely need to chunk them and that is your issue.
Firefox supports much bigger messages by design, but you will get compatibility issues if you send those to other browsers.
Simple-peer supports Node.js stream API that allows you to conveniently manage sending data as soon as possible, I'd suggest you to chunk data into messages and use that to send them (you'll need to re-assemble messages on the other side of course).

Closing since there doesn't seem to be anything that should be fixed in simple-peer, but feel free to continue conversation.

**Closed by nazar-pc** 2020-07-23 21:40 UTC
Labels: question
