### ISSUE TITLE
TypeError: The expression cannot be converted to return the specified type.

### ISSUE THREAD

**Issue by Arcath** [feross/simple-peer#460] opened 2019-04-30 15:09 UTC
I have a file sending app that works fine on localhost with local testing but when hosted remotely even when the two browsers are on the same computer I get this error:

`TypeError: The expression cannot be converted to return the specified type.`

Which is thrown from here: https://github.com/feross/simple-peer/blob/master/index.js#L243

Not sure why it's happening only on remote. If it helps the apps source is here: https://github.com/Arcath/file-from-me

**Comment by t-mullen** [comment] 2019-05-05 00:37
What type are you passing to `peer.send` or `peer.write`?

**Comment by Arcath** [comment] 2019-05-07 09:45
I'm just using a string which is the output of `JSON.stringify`.

**Comment by t-mullen** [comment] 2019-05-08 15:28
Which browser and browser version?

**Comment by EnrootingTech** [comment] 2019-05-20 21:30
I am getting the samething, this happens when using FireFox, but I believe everything is setup well.

When trying to send a chunk of arrayBuffer type throught datachannel FireFox gives me this.

TypeError: The expression cannot be converted to return the specified type. Also sometimes I get unexpected errors, If I may asks what makes the datachannel to closed by itself?

**Comment by t-mullen** [comment] 2019-05-21 00:02
I need a Firefox version to try and reproduce this bug.

**Comment by kay-master** [comment] 2019-05-21 07:28
FireFox version 66.0.3,

**Comment by nwoltman** [comment] 2019-07-22 19:23
I found the reason for this. Firefox respects the max message size of the peer it is connected to, so if you try to send data larger than the max message size, Firefox throws this error. The default max message size is `65535` if the peer does not provide it (and currently no browser provides it other than Firefox).

So if you're sending data larger than `65535` bytes, this is probably the source of the error.

**Comment by t-mullen** [comment] 2019-12-13 03:13
Tracking in #546

**Closed by t-mullen** 2019-12-13 03:13 UTC
