### ISSUE TITLE
Rollup support

### ISSUE THREAD

**Issue by AlbertoElias** [feross/simple-peer#205] opened 2017-10-28 17:53 UTC
I'm trying to use this in a library I'm working on that I'd like to build with Rollup to support ES6 modules. It doesn't seem to be compiling properly with Rollup. I did a [small test case](https://gist.github.com/AlbertoElias/2641c23cc8dc256b29bc4c018e1888fa) to try it out.

I raised the issue in [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/35), and they pointed to `readable-stream`

**Comment by RationalCoding** [comment] 2017-10-28 19:37
The problem is in readable-stream. Is this a duplicate of readable-stream#237?

**Comment by RationalCoding** [comment] 2017-10-31 22:45
Closing as the problem is with `readable-stream`.

**Closed by RationalCoding** 2017-10-31 22:45 UTC

**Comment by AlbertoElias** [comment] 2017-11-01 12:32
Well, looking into that issue, it feels like it could be fixed if simple-peer used stream instead of readable-stream

**Comment by RationalCoding** [comment] 2017-11-01 19:09
readable-stream lets us use Streams2 on older versions of Node, as well as being more stable. Changing deps might cause more problems.

It's meant to mirror the stream module, so if stream works in Rollup, I'd mention that in the linked issue.

If you want to use stream for your personal build, you could override the sub-dependency with npm-shrinkwrap.

**Comment by AlbertoElias** [comment] 2017-11-16 18:33
Ended up going with this: https://github.com/rollup/rollup-plugin-alias/issues/33
