### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by StephenK9** [feross/simple-peer#534] opened 2019-08-18 07:43 UTC
Beginner to WebRTC here. I've set up a https signal server with websockets. When I connect to the signal server with devices that reside within the same wifi network (PC, mobile etc) everything works fine (video/audio work perfectly). However, if I try to connect to another device that is not in the same wifi network, no video/audio gets received. No data gets transmitted. No errors log to console. I'm using the default google STUN servers specified by simple-peer. I suspect this issue is related to TURN servers? What else could cause this issue? Thanks!

**Comment by nazar-pc** [comment] 2019-08-18 13:22
Yes, it is most likely caused by devices not being able to establish direct connection and you may need to tweak router configuration or use TURN servers.

You can find more information about why connection is not established by going to `about:webrtc` in Firefox and `chrome://webrtc-logs` + `chrome://webrtc-internals` in Chromium-based browsers.

I'm closing issue since this is not an issue with simple-peer, but feel free to continue conversation.

**Closed by nazar-pc** 2019-08-18 13:22 UTC
Labels: question
