### ISSUE TITLE
Ice connection failed when using peer.signal(signal) on Safari 13.1.2 on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by benjiJanssens** [feross/simple-peer#707] opened 2020-07-16 18:44 UTC
Whenever I use peer.signal(signal) on Safari 13.1.2 on macOS Catalina 10.15.6, I get an "ice connection failed" error. On the other device, Chrome on Windows on the same network in this case, I get a "connection failed" error. This is, however, fixed when using a TURN server, giving access to the microphone and/or webcam or disabling ICE candidate restrictions in Safari, but all of these options are not a solution for my application because they are not user-friendly at all.

Is this a bug? Is this intentional? Or has it got nothing to do with simple-peer, but is it all WebRTC?

In the past I have made use of simple-signal, which didn't have this behaviour. Could that be the case because the whole connection-making takes place on the server?

Update: just tested and seems to be working in the Safari Technology Preview (14.0)
Update 2: also sending from Safari 13.1.2 to the Safari Technology Preview (14.0) seems to be working fine
Update 3: sending from Safari 13.1.2 to Safari 13.1.2 also doesn't work though

**Comment by nazar-pc** [comment] 2020-07-16 20:26
If something works with TURN and doesn't without, it means direct connection can't be established. This is not a bug, this is a standard thing when working with WebRTC. Library can't do anything about Safari's restrictions.

This doesn't seem to be anything about simple-peer indeed and something specific to Safari's unique implementation of WebRTC that historically had and still has a lot of issues. Good news that some more of this issues are fixed with TP 14.

**Comment by nazar-pc** [comment] 2020-07-16 20:27
I don't remember if Safari support mDNS, that can also be the source of issues in local network if browser doesn't know how to deal with it.

**Comment by feross** [comment] 2020-07-17 03:21
Closing but feel free to continue discussion.

**Closed** 2020-07-17 03:21 UTC
Labels: question

**Comment by benjiJanssens** [comment] 2020-07-17 09:56
Would there a way to bypass these restrictions like simple-signal does? For instance letting the connection take place on the signaling server, if that's how they do it?

**Comment by nazar-pc** [comment] 2020-07-17 10:01
I don't know what simple-signal is, but as you mentioned, TURN reachable by both peers is the solution if P2P connection is not available.

**Comment by benjiJanssens** [comment] 2020-07-17 12:33
Isn't TURN a little overkill if you're on the same network? My application is supposed to only connect devices on the same network.

**Comment by nazar-pc** [comment] 2020-07-17 12:44
Well, if it works without - yes, if it doesn't...
You need to debug why is that happening exactly first. Maybe there is something that can be tweaked in the network itself to make it work.
