### ISSUE TITLE
Bug [sdpTransform]: After modification fails to connect

### ISSUE THREAD

**Issue by dalisoft** [feross/simple-peer#614] opened 2020-04-08 15:20 UTC
Hi, thanks for such a great library.

This makes our development easier.
I today tried to modify `codec` and `bitrate`, but failing both failed.

## Code
```js
/* globals window, document, SimplePeer, WebSocket */
/* eslint-disable no-underscore-dangle, no-param-reassign, no-console */

const p = document.querySelector('#info');
const main = document.querySelector('main');
const video = document.querySelector('.video');

const WIDTH = 360;
const HEIGHT = 360;
const FPS = 24;

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string:q
}

function sdpFilterCodec(kind, codec, realSdp) {
  var allowed = []
  var rtxRegex = new RegExp('a=fmtp:(\\d+) apt=(\\d+)\r$');
  var codecRegex = new RegExp('a=rtpmap:([0-9]+) ' + escapeRegExp(codec))
  var videoRegex = new RegExp('(m=' + kind + ' .*?)( ([0-9]+))*\\s*$')

  var lines = realSdp.split('\n');

  var isKind = false;
  for (var i = 0; i < lines.length; i++) {
      if (lines[i].startsWith('m=' + kind + ' ')) {
          isKind = true;
      } else if (lines[i].startsWith('m=')) {
          isKind = false;
      }

      if (isKind) {
          var match = lines[i].match(codecRegex);
          if (match) {
              allowed.push(parseInt(match[1]));
          }

          match = lines[i].match(rtxRegex);
          if (match && allowed.includes(parseInt(match[2]))) {
              allowed.push(parseInt(match[1]));
          }
      }
  }

  var skipRegex = 'a=(fmtp|rtcp-fb|rtpmap):([0-9]+)';
  var sdp = '';

  isKind = false;
  for (var i = 0; i < lines.length; i++) {
      if (lines[i].startsWith('m=' + kind + ' ')) {
          isKind = true;
      } else if (lines[i].startsWith('m=')) {
          isKind = false;
      }

      if (isKind) {
          var skipMatch = lines[i].match(skipRegex);
          if (skipMatch && !allowed.includes(parseInt(skipMatch[2]))) {
              continue;
          } else if (lines[i].match(videoRegex)) {
              sdp += lines[i].replace(videoRegex, '$1 ' + allowed.join(' ')) + '\n';
          } else {
              sdp += lines[i] + '\n';
          }
      } else {
          sdp += lines[i] + '\n';
      }
  }

  return sdp;
}

function updateBandwidthRestriction(sdp, bandwidth) {
  let modifier = 'AS';
  if (/firefox/.test(navigator.userAgent)) {
    bandwidth = (bandwidth >>> 0) * 1000;
    modifier = 'TIAS';
  }
  if (sdp.indexOf('b=' + modifier + ':') === -1) {
    // insert b= after c= line.
    sdp = sdp.replace(/c=IN (.*)\r\n/, 'c=IN $1\r\nb=' + modifier + ':' + bandwidth + '\r\n');
  } else {
    sdp = sdp.replace(new RegExp('b=' + modifier + ':.*\r\n'), 'b=' + modifier + ':' + bandwidth + '\r\n');
  }
  return sdp;
}

function createSdpTransform(codec, bandwidth = 3600) {
  if (codec === undefined) {
    codec = window.chrome ? 'vp9': 'vp8'
  }
  return (sdp) => {
    sdp = sdpFilterCodec('video', codec, sdp);
    sdp = updateBandwidthRestriction(sdp, bandwidth);

    return sdp;
  }
}

function initOnStream(stream) {
  const peerClient = new SimplePeer({
    initiator: true,
    sdpTransform: createSdpTransform(window.chrome ? 'vp9' : 'vp8', 500),
    trickle: false,
    reconnectTimer: 100,
    iceTransportPolicy: 'relay',
    objectMode: true
  });

  peerClient.on('stream', (stream) => {
    try {
      video.srcObject = stream;
    } catch (error) {
      video.src = window.URL.createObjectURL(stream);
    }
    return stream;
  })
  peerClient.on('signal', (data) => {
    return fetch('/offer', {
        body: JSON.stringify(data),
        headers: {
            'Content-Type': 'application/json'
        },
        method: 'POST'
    }).then(res => res.json()).then(signal => peerClient.signal(signal));
  })
  peerClient.on('connect', () => {
    console.log('Peer Connected');
  });
  peerClient.on('error', (e) => {
    console.error('Peer error', e);
  });
  peerClient.on('close', (e) => {
    console.log('Peer closed', e);
  });

  peerClient.addTrack(stream.getTracks()[0], stream);
}

window
  .getMedia({
    video: {
      width: WIDTH,
      height: HEIGHT,
      frameRate: FPS
    },
    facingMode: 'user',
    audio: false
  })
  .then((stream) => {
    try {
      video.srcObject = stream;
    } catch (error) {
      video.src = window.URL.createObjectURL(stream);
    }
    return stream;
  })
  .then(initOnStream);

```

Code was used from which works fine: [1](https://github.com/aiortc/aiortc/blob/master/examples/server/client.js), [2](https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/bandwidth/js/main.js#L225)

## Error

```log
[Error] Peer error – Error: OperationError: Invalid SDP line. — simplepeer.min.js:6:79436
Error: OperationError: Invalid SDP line. — simplepeer.min.js:6:79436a — simplepeer.min.js:6:79436https://unpkg.com/simple-peerpromiseReactionJob
	(анонимная функция) (client.js:120)
	d (simplepeer.min.js:6:27893)
	(анонимная функция) (simplepeer.min.js:6:31460)
	_destroy (simplepeer.min.js:6:86745)
	destroy (simplepeer.min.js:6:85696)
	(анонимная функция) (simplepeer.min.js:6:88898)
	promiseReactionJob
```

## Note

- Maybe i'm doing something wrong?
- Is there any library to handle this for `simple-peer`?
- Can i change `codec` and `bitrate` at all?

Thanks

**Comment by nazar-pc** [comment] 2020-04-08 23:04
The issue is clear and is not even fired by simple-peer:
> Invalid SDP line

So SDP editing is done incorrectly and needs to be fixed. Try to simplify it and find what is wrong exactly. There have been questions like this before like this one recently with suggested approach to changing codec priority: #607

Since the issue is not with simple-peer, I'm closing this, but feel free to continue conversation.

**Closed by nazar-pc** 2020-04-08 23:04 UTC
Labels: question
