### ISSUE TITLE
Peer.config iceServers format

### ISSUE THREAD

**Issue by Xazzzi** [feross/simple-peer#166] opened 2017-04-07 22:08 UTC
So i've been digging it for a while #163, but eventually figured out that `wrtc` expects `iceServers` in different format. Defaut is:
```
// index.js:152
Peer.config = {
  iceServers: [{urls: '<string>'}, ...]
}
```
I don't know how spec says, but `wrtc` actually expects:
```
Peer.config = {
  iceServers: {
    urls: ['<string>', ...]
  }
}
```
After i overrided default config my peer connection is not dropped anymore and `signalingStatus` is `stable`. Hope this could help somebody.

**Comment by Xazzzi** [comment] 2017-04-07 22:32
Testing different formats of iceServers config property:
```
// Urls as array
{urls: [String]} - works
[{urls: [String]}] - works
// Urls as string
{urls: String} - works
[{urls: String}] - fails (default config format in simple-peer)
```
With more than one ice server, `urls` as string is not allowed by `wrtc`.

**Comment by RationalCoding** [comment] 2017-04-07 22:52
(All formats are supported by the spec and they should all work.)[https://www.w3.org/TR/webrtc/#dom-rtciceserver]

I haven't been able to reproduce with:

```
Peer.config = {
  iceServers: [
    {
      urls: 'stun:stun.l.google.com:19302'
    }
  ]
}
```

Can you post your test case?

**Comment by RationalCoding** [comment] 2017-04-07 23:06
It looks like `wrtc` has added some additional code to support the non-compliant formats, but that should be fine.

[peerconnection.cc Line 254](https://github.com/js-platform/node-webrtc/pull/295/commits/3d1dd1f3881315b1aceaa58bd8b07e9b2b6ff5f7)

**Comment by RationalCoding** [comment] 2017-04-07 23:13
I found the issue. `wrtc` only supports a string if the property is `url`, not `urls`. This is not correct.

```
              else if (iceServerKey == "urls" && iceValue->IsArray()) {
                Handle<Array> iceUrls = Handle<Array>::Cast(iceValue);

                for (uint32_t x = 0; x < iceUrls->Length(); x++) {
                  String::Utf8Value _iceUrlsEntry(iceUrls->Get(x)->ToString());
                  std::string iceUrlsEntry = std::string(*_iceUrlsEntry);

                  iceServer.urls.push_back(iceUrlsEntry);
                }
              }
```

Opening an issue in `node-webrtc` and closing this.

**Closed by RationalCoding** 2017-04-07 23:13 UTC
