### ISSUE TITLE
Data connection works but video not streaming?

### ISSUE THREAD

**Issue by teeramusic** [feross/simple-peer#142] opened 2017-02-09 07:15 UTC
This is the peer with the camera (some info might be missing because I used just JSON.stringify) except I added the steam info as I can see in console.log()

this peer was instantiated with `var peer = new SimplePeer({stream: video.stream}); `

``` "{"
_id ":"
0 cb1b63 ","
_readableState ":{"
objectMode ":false,"
highWaterMark ":1048576,"
buffer ":{"
head ":null,"
tail ":null,"
length ":0},"
length ":0,"
pipes ":null,"
pipesCount ":0,"
flowing ":true,"
ended ":false,"
endEmitted ":false,"
reading ":true,"
sync ":false,"
needReadable ":true,"
emittedReadable ":false,"
readableListening ":false,"
resumeScheduled ":false,"
defaultEncoding ":"
utf8 ","
ranOut ":false,"
awaitDrain ":0,"
readingMore ":false,"
decoder ":null,"
encoding ":null},"
readable ":true,"
_events ":{},"
_writableState ":{"
objectMode ":false,"
highWaterMark ":1048576,"
needDrain ":false,"
ending ":false,"
ended ":false,"
finished ":false,"
decodeStrings ":true,"
defaultEncoding ":"
utf8 ","
length ":0,"
writing ":false,"
corked ":0,"
sync ":true,"
bufferProcessing ":false,"
writecb ":null,"
writelen ":0,"
bufferedRequest ":null,"
lastBufferedRequest ":null,"
pendingcb ":0,"
prefinished ":false,"
errorEmitted ":false,"
bufferedRequestCount ":0,"
corkedRequestsFree ":{"
next ":null,"
entry ":null}},"
writable ":true,"
allowHalfOpen ":false,"
channelName ":"
9 dd132f7c260e715b3d96ff77fb911034d1df192 ","
initiator ":false,"
channelConfig ":{},"
config ":{"
iceServers ":[{"
urls ":"
stun: stun.l.google.com: 19302 "}]},"
constraints ":{},"
offerConstraints ":{},"
answerConstraints ":{},"
reconnectTimer ":false,"
stream ":{
MediaStream
active:true,
id:"9UwXcxzzHsiTzscKjJLXr1rmHktKLjT4GTMt"
onactive:null
onaddtrack:null
oninactive:null
onremovetrack:null
},"
trickle ":true,"
destroyed ":false,"
connected ":true,"
remoteAddress ":"
fdd4: a148: 744 c: 4700: 5973: 54 a9: f2ab: f640 ","
remoteFamily ":"
IPv4 ","
remotePort ":53731,"
localAddress ":"
2001::9 d38: 90 d7: cf2: 18 f2: 54 fb: 657 ","
localPort ":58258,"
_wrtc ":{},"
_maxBufferedAmount ":1048576,"
_pcReady ":true,"
_channelReady ":true,"
_iceComplete ":true,"
_channel ":{},"
_pendingCandidates ":[],"
_chunk ":null,"
_cb ":null,"
_interval ":10,"
_reconnectTimeout ":null,"
_pc ":{},"
_isWrtc ":false,"
_isReactNativeWebrtc ":false,"
_connecting ":false}"
```

This is the other peer...
instantiated with ` peer = new SimplePeer({initiator:true});`

``` "{"
_id ":"
381 d378 ","
_readableState ":{"
objectMode ":false,"
highWaterMark ":1048576,"
buffer ":{"
head ":null,"
tail ":null,"
length ":0},"
length ":0,"
pipes ":null,"
pipesCount ":0,"
flowing ":true,"
ended ":false,"
endEmitted ":false,"
reading ":true,"
sync ":false,"
needReadable ":true,"
emittedReadable ":false,"
readableListening ":false,"
resumeScheduled ":false,"
defaultEncoding ":"
utf8 ","
ranOut ":false,"
awaitDrain ":0,"
readingMore ":false,"
decoder ":null,"
encoding ":null},"
readable ":true,"
_events ":{},"
_writableState ":{"
objectMode ":false,"
highWaterMark ":1048576,"
needDrain ":false,"
ending ":false,"
ended ":false,"
finished ":false,"
decodeStrings ":true,"
defaultEncoding ":"
utf8 ","
length ":0,"
writing ":false,"
corked ":0,"
sync ":true,"
bufferProcessing ":false,"
writecb ":null,"
writelen ":0,"
bufferedRequest ":null,"
lastBufferedRequest ":null,"
pendingcb ":0,"
prefinished ":false,"
errorEmitted ":false,"
bufferedRequestCount ":0,"
corkedRequestsFree ":{"
next ":null,"
entry ":null}},"
writable ":true,"
allowHalfOpen ":false,"
channelName ":"
9 dd132f7c260e715b3d96ff77fb911034d1df192 ","
initiator ":true,"
channelConfig ":{},"
config ":{"
iceServers ":[{"
urls ":"
stun: stun.l.google.com: 19302 "}]},"
constraints ":{},"
offerConstraints ":{},"
answerConstraints ":{},"
reconnectTimer ":false,"
stream ":false,"
trickle ":true,"
destroyed ":false,"
connected ":true,"
_wrtc ":{},"
_maxBufferedAmount ":1048576,"
_pcReady ":true,"
_channelReady ":true,"
_iceComplete ":true,"
_channel ":{},"
_pendingCandidates ":[],"
_chunk ":null,"
_cb ":null,"
_interval ":4,"
_reconnectTimeout ":null,"
_pc ":{},"
_isWrtc ":false,"
_isReactNativeWebrtc ":false,"
_connecting ":false}"
```

It seems like on `'stream'` on the receiving peer never got called. They live in two separate windows.
`.send('some message')` works and the peers can talk to each other.

**Comment by teeramusic** [comment] 2017-02-09 07:27
This is the sdp (for a different session, so some values might be a bit different)
``` { type: 'offer',
     sdp: 'v=0\r\no=- 7427354299586564711 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:4Ug6\r\na=ice-pwd:ALPKMpxT7ckPmcseGE86DWdk\r\na=fingerprint:sha-256 B6:84:40:C5:DD:A6:21:5B:21:D0:4B:3A:C7:F6:34:DF:54:41:23:3B:5B:1D:A8:3D:1E:5D:0B:93:3E:38:65:79\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' } }
sending message {"action":"signal","target":2,"data":{"type":"offer","sdp":"v=0\r\no=- 7427354299586564711 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:4Ug6\r\na=ice-pwd:ALPKMpxT7ckPmcseGE86DWdk\r\na=fingerprint:sha-256 B6:84:40:C5:DD:A6:21:5B:21:D0:4B:3A:C7:F6:34:DF:54:41:23:3B:5B:1D:A8:3D:1E:5D:0B:93:3E:38:65:79\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}
```
```   { type: 'answer',
     sdp: 'v=0\r\no=- 9013576120661992134 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:YbDK\r\na=ice-pwd:RLOM3lnHKKqJBWop2Zmnh266\r\na=fingerprint:sha-256 F3:87:46:07:B1:9C:BE:D7:DF:87:6A:66:88:F3:75:7A:AD:4C:AB:5D:10:52:1F:4A:DA:A2:16:D1:E4:F4:FD:31\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n' } }
sending message {"action":"signal","target":2,"data":{"type":"answer","sdp":"v=0\r\no=- 9013576120661992134 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=ice-ufrag:YbDK\r\na=ice-pwd:RLOM3lnHKKqJBWop2Zmnh266\r\na=fingerprint:sha-256 F3:87:46:07:B1:9C:BE:D7:DF:87:6A:66:88:F3:75:7A:AD:4C:AB:5D:10:52:1F:4A:DA:A2:16:D1:E4:F4:FD:31\r\na=setup:active\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}
```

**Comment by teeramusic** [comment] 2017-02-09 17:58
If it makes any difference, I'm using https

**Comment by RationalCoding** [comment] 2017-02-12 06:01
Is the initiator *not* providing a video stream while the other peer is? @teeramusic

**Comment by feross** [comment] 2017-02-14 00:12
Closing as a duplicate of https://github.com/feross/simple-peer/issues/95.

@teeramusic There is a workaround in that issue. Hope that helps!

**Closed by feross** 2017-02-14 00:12 UTC

**Comment by teeramusic** [comment] 2017-02-14 02:15
Thanks! That's what I ended up doing. The peer that was initiating now sends a WS "initiation request" to the other peer so that the peer with the stream can be the actual webrtc initiator instead. The strange thing was that I tried #95 in the same window (so without websocket) and it worked, so I initially thought maybe it was some mistake on my part.
