### ISSUE TITLE
Error: cannot signal after peer is destroyed

### ISSUE THREAD

**Issue by ChrisK1994** [feross/simple-peer#753] opened 2020-10-26 23:55 UTC
This error happens to me when I try to connect for the second time after destroying peers(and creating new).
```
    socket.current.on("peer", (data) => {
      setPartner(data.peerId);
      let peerId = data.peerId;
      let peer = new Peer({
        initiator: data.initiator,
        trickle: true,
        config: {
          iceServers: [
            {
              urls: "stun:numb.viagenie.ca",
              username: "sultan1640@gmail.com",
              credential: "98376683",
            },
            {
              urls: "turn:numb.viagenie.ca",
              username: "sultan1640@gmail.com",
              credential: "98376683",
            },
          ],
        },
        stream: userVideo.current.srcObject,
      });
      myPeer.current = peer;

      socket.current.on("signal", (data) => {
        if (data.peerId === peerId) {
          peer.signal(data.signal);
        }
      });
      socket.current.on("close", () => {
        setChatOnline(false);
        myPeer.current.destroy();
      });
      peer.on("signal", (data) => {
        socket.current.emit("signal", {
          signal: data,
          peerId: peerId,
        });
      });
      peer.on("error", (e) => {
      });
      peer.on("connect", () => {
        peer.send("hey peer");
      });
      peer.on("data", (data) => {
        console.log(data);
      });
      peer.on("stream", (stream) => {
        setChatOnline(true);
        setSearchingPartner(false);
        partnerVideo.current.srcObject = stream;
      });
      peer.on('close', () => {
        setChatOnline(false);
      })
      peers[peerId] = peer;
    });
```
and back:

```
  socket.on("findPartner", (data) => {
      partnerSocket.emit("peer", {
        peerId: socket.id,
        initiator: true,
      });
      socket.emit("peer", {
        peerId: partnerSocket.id,
        initiator: false,
      });
  });

  socket.on("signal", (data) => {
    var socket2 = io.sockets.connected[data.peerId];
    if (!socket2) {
      return;
    }

    socket2.emit("signal", {
      signal: data.signal,
      peerId: socket.id,
    });
  });
```

**Comment by feross** [comment] 2020-10-27 04:14
It looks like you need to unregister the old event handlers so they don't call functions on the old peer object.

Closing since this isn't an issue with `simple-peer`.

**Closed by feross** 2020-10-27 04:14 UTC

**Comment by jcubic** [comment] 2022-11-26 20:37
@feross I have the same issue and it's related to SimplePeer because it happens when a new peer disconnects.  But instead of properly destroying it signals the error (that can be caught by `peer.on('error', () => {})`:

```
RTCError: User-Initiated Abort, reason=Close called
```

I'm not sure why but the signal to destroy the peer never reaches and the next time you try to send a message it throws: `simplepeer.min.js:6 Uncaught (in promise) Error: cannot send after peer is destroyed`.


Is there a way to figure out which peer is giving error and don't close properly? Why did I have this error in the first place? It seems that it's improper handling of WebRTC by the library.

This is my code: https://codepen.io/jcubic/pen/xxzjQRd?editors=0010 I think I have everything correctly written but it sometimes fails probably because of some error in WebRTC that is not handled properly. I didn't investigate yet if my message that calls destroy is always sent (I use the automated feature of Firebase real-time database), but it would be not sent it only will make the peer hang and not signal an error.

**Comment by jcubic** [comment] 2022-11-26 20:47
I've got this error after the peer closes the connection (it cannot be stringified):

![Przechwycenie obrazu ekranu_2022-11-26_21-46-49](https://user-images.githubusercontent.com/280241/204108297-a58198c9-9ea6-4c3a-a39e-ae8b1df6fd0e.png)

The problem is that the close event doesn't give a clue which peer disconnected.

**Comment by jcubic** [comment] 2022-11-26 20:59
I think that this happens when `peer.destroy()` is called after a delay. This is what I have in console:
```
[21:57:59] 80241981 Ready
{ERROR: RTCError: User-Initiated Abort, reason=Close called}
{CLOSE: undefined}
[21:58:05] 80241981 disconnected
```

**Comment by jcubic** [comment] 2022-11-26 21:16
So I think that this is something with WebRTC that is not handled by the library.
But you can prevent sending the message to broken peer if you use:

```javascript
if (peer.writable) {
   peer.send('something');
}
```
